#ifndef FRAKTALE_FRACTALIDENTIFIERS_HPP
#define FRAKTALE_FRACTALIDENTIFIERS_HPP

namespace Fractals {
  enum ID {
    EMPTY_FRACTAL,
    MANDELBROT
  };
}

Q_DECLARE_METATYPE(Fractals::ID);

#endif //FRAKTALE_FRACTALIDENTIFIERS_HPP
